databases:
  - name: postgresql
    region: frankfurt

services:
  - type: web
    name: jurnlog # Part of URL.
    region: frankfurt
    env: ruby
    buildCommand: bundle install; bundle exec rake assets:precompile; bundle exec rake assets:clean; bundle exec rake db:migrate;
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgresql
          property: connectionString
      - key: SECRET_KEY_BASE
        sync: false