databases:
  - name: jlpq
    databaseName: postgrjlpqesql
    user: jlpq
    region: ohio


services:
  - type: web
    name: rails-web
    env: ruby
    region: ohio
    buildCommand: bundle install; bundle exec rake assets:precompile; bundle exec rake assets:clean; bundle exec rake db:migrate;
    startCommand: bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-development}
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: jlpq
          property: connectionString
      - key: SECRET_KEY_BASE
        sync: false